ACCEPTED = 'accepted'
REJECTED = 'rejected'
WAITING = 'waiting'

DRAFT = 'draft'
SUBMITTED = 'submitted'

ADMIN_STATE_CHOICES = (
    (ACCEPTED, ACCEPTED),
    (REJECTED, REJECTED),
    (WAITING, WAITING),
)

STUDENT_STATE_CHOICES = (
    (DRAFT, DRAFT),
    (SUBMITTED, SUBMITTED),
)

STATE_CHOICES = ADMIN_STATE_CHOICES + STUDENT_STATE_CHOICES
