# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 09:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0017_language_changed'),
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True)),
                ('birth_location', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male'), ('U', 'unknown')], default='U', max_length=1, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('high_school_diploma', models.BooleanField()),
                ('high_school_graduation_year', models.DateField(blank=True)),
                ('last_degree_level', models.CharField(blank=True, max_length=50, null=True)),
                ('last_degree_field', models.CharField(blank=True, max_length=50, null=True)),
                ('last_degree_institution', models.CharField(blank=True, max_length=50, null=True)),
                ('last_degree_graduation_year', models.DateField(blank=True)),
                ('other_educational_background', models.TextField(blank=True, null=True)),
                ('professional_status', models.CharField(blank=True, choices=[('EMPLOYEE', 'employee'), ('SELF_EMPLOYED', 'self_employed'), ('JOB_SEEKER', 'job_seeker'), ('PUBLIC_SERVANT', 'public_servant')], max_length=50, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('past_professional_activities', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('professional_impact', models.TextField(blank=True, null=True)),
                ('formation_title', models.CharField(blank=True, max_length=50, null=True)),
                ('courses_formula', models.CharField(blank=True, max_length=50, null=True)),
                ('program_code', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('formation_administrator', models.CharField(blank=True, max_length=50, null=True)),
                ('ucl_website', models.BooleanField()),
                ('formation_website', models.BooleanField()),
                ('press', models.BooleanField()),
                ('facebook', models.BooleanField()),
                ('linkedin', models.BooleanField()),
                ('customized_mail', models.BooleanField()),
                ('emailing', models.BooleanField()),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
            ],
        ),
    ]
