# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='customized_mail',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='emailing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='facebook',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='formation_website',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='linkedin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='press',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ucl_website',
            field=models.BooleanField(null=True),
        ),
    ]
