# Generated by Django 2.2.13 on 2021-05-26 07:55

import continuing_education.models.file
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osis_common.utils.validators
import uuid


class Migration(migrations.Migration):
    replaces = [('continuing_education', '0085_auto_20210423_1545'), ('continuing_education', '0086_auto_20210428_1409')]

    initial = True

    dependencies = [
        ('continuing_education', '0001_squashed_0084_auto_20210127_1119'),
        ('base', '0583_auto_20210324_0954'),
    ]

    operations = [
    ]
