# Generated by Django 2.2.24 on 2022-03-15 08:26

import logging

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Cast

logger = logging.getLogger(settings.DEFAULT_LOGGER)


def populate_created_at(apps, schema_editor):
    logger.info('Updating new admission.create_at with information from reversion')
    Admission = apps.get_model('continuing_education', 'Admission')
    try:
        Version = apps.get_model('reversion', 'Version')

        admissions = Admission.objects.filter(created_at__isnull=True)
        filter_by_comment = Q(revision__comment__contains="Création de l'admission") | Q(revision__comment__contains="Creation of the admission")
        for admission in admissions:
            versions = Version.objects\
                .annotate(object_id_casted=Cast('object_id', models.CharField()))\
                .filter(
                    content_type__model='admission',
                    object_id_casted=Cast(admission.pk, models.CharField()))\
                .filter(filter_by_comment).select_related(
                    "revision",
                )
            if versions:
                logger.info(versions[0].revision.date_created)
                admission.created_at = versions[0].revision.date_created
                admission.save()
    except LookupError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0002_squashed_0086'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Creation date'),
        ),
        migrations.RunPython(populate_created_at, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
