# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 10:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0002_auto_20180629_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_country', to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='customized_mail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='emailing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='facebook',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='formation_website',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='linkedin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='press',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='ucl_website',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
