# Generated by Django 3.2.12 on 2022-09-26 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0003_admission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
