# Generated by Django 3.2.12 on 2022-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0004_prospect_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='ucl_registration_complete',
            field=models.CharField(blank=True, choices=[('INIT_STATE', 'Initial state'), ('SENDED', 'Sended'), ('INSCRIT', 'Registered'), ('DEMANDE', 'On demand'), ('REJECTED', 'Rejected'), ('NON_RENSEIGNE', 'Uninformed'), ('CONDITION', 'Provisional'), ('ANNULATION_ETD', 'Cancellation (ETD)'), ('ANNULATION_UCL', 'Cancellation (UNIV)'), ('EXCLUSION', 'Exclusion'), ('CESSATION', 'Cessation'), ('DECES', 'Death'), ('ERREUR', 'Error'), ('INTENTION_ECHANGE', 'Register intention'), ('ANNULATION_ECHANGE', 'Intention cancellation'), ('REINSCRIPTION_WEB', 'Internet re-registration'), ('ANNULATION_IP', 'IP Cancellation'), ('REFUS', 'Refusal'), ('CYCLE', 'Cycle'), ('VALISE_CREDITS', 'Valued credits')], default='INIT_STATE', max_length=50, verbose_name='UCLouvain registration complete'),
        ),
    ]
