# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0004_auto_20180807_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='formation_spreading',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
