# Generated by Django 3.2.25 on 2024-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0005_alter_admission_ucl_registration_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationmanager',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='continuingeducationstudentworker',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='continuingeducationtrainingmanager',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
