# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0006_auto_20180824_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='assessment_succeded',
            new_name='assessment_succeeded',
        ),
        migrations.AlterField(
            model_name='admission',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('PUBLIC', 'public'), ('ASSOCIATIVE', 'associative'), ('HEALTH', 'health'), ('OTHER', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], default='F', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'single'), ('MARRIED', 'married'), ('WIDOWED', 'widowed'), ('DIVORCED', 'divorced'), ('SEPARATED', 'separated'), ('LEGAL_COHABITANT', 'legal_cohabitant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='professional_status',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'employee'), ('SELF_EMPLOYED', 'self_employed'), ('JOB_SEEKER', 'job_seeker'), ('PUBLIC_SERVANT', 'public_servant'), ('OTHER', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('PROFESSIONAL', 'professional')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('waiting', 'waiting')], max_length=50, null=True),
        ),
    ]
