# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0008_auto_20180830_1654'),
    ]

    operations = []
