# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 11:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0008_auto_20180830_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='formation_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_title', to='base.OfferYear'),
        ),
    ]
