# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 15:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0342_auto_20180830_1605'),
        ('continuing_education', '0009_auto_20180831_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='formation_title',
        ),
        migrations.AddField(
            model_name='admission',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
