# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0011_auto_20180904_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EntityVersion'),
        ),
    ]
