# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 10:45
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_domain_changed'),
        ('continuing_education', '0013_auto_20180905_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('birth_location', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], default='F', max_length=1)),
                ('phone_mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('high_school_diploma', models.BooleanField(default=False)),
                ('high_school_graduation_year', models.DateField(blank=True, default=datetime.datetime.now)),
                ('last_degree_level', models.CharField(blank=True, max_length=50)),
                ('last_degree_field', models.CharField(blank=True, max_length=50)),
                ('last_degree_institution', models.CharField(blank=True, max_length=50)),
                ('last_degree_graduation_year', models.DateField(blank=True, default=datetime.datetime.now)),
                ('other_educational_background', models.TextField(blank=True)),
                ('professional_status', models.CharField(blank=True, choices=[('EMPLOYEE', 'employee'), ('SELF_EMPLOYED', 'self_employed'), ('JOB_SEEKER', 'job_seeker'), ('PUBLIC_SERVANT', 'public_servant'), ('OTHER', 'other')], max_length=50)),
                ('current_occupation', models.CharField(blank=True, max_length=50)),
                ('current_employer', models.CharField(blank=True, max_length=50)),
                ('activity_sector', models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('PUBLIC', 'public'), ('ASSOCIATIVE', 'associative'), ('HEALTH', 'health'), ('OTHER', 'other')], max_length=50)),
                ('past_professional_activities', models.TextField(blank=True)),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_country', to='reference.Country')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='reference.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='reference.Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='admission',
            name='activity_sector',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='city',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='courses_formula',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='formation_administrator',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='high_school_diploma',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='high_school_graduation_year',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_degree_field',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_degree_graduation_year',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_degree_institution',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_degree_level',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='other_educational_background',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='past_professional_activities',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='professional_status',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='program_code',
        ),
        migrations.AddField(
            model_name='admission',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Person'),
        ),
    ]
