# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0014_auto_20180911_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.PersonAddress'),
        ),
    ]
