# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 15:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_domain_changed'),
        ('continuing_education', '0016_auto_20180911_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='reference.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personaddress',
            name='person',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
        migrations.AlterField(
            model_name='admission',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='continuing_education.Address'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_address', to='continuing_education.Address'),
        ),
        migrations.DeleteModel(
            name='PersonAddress',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Address'),
        ),
    ]
