# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Address = apps.get_model('continuing_education', 'Address')
    Admission = apps.get_model('continuing_education', 'Admission')
    ContinuingEducationPerson = apps.get_model('continuing_education', 'ContinuingEducationPerson')

    for row in Address.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    for row in Admission.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    for row in ContinuingEducationPerson.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0018_auto_20181004_0018'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]