# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-22 09:51
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_domain_changed'),
        ('continuing_education', '0023_auto_20181017_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='activity_sector',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='high_school_diploma',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='high_school_graduation_year',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='last_degree_field',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='last_degree_graduation_year',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='last_degree_institution',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='last_degree_level',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='other_educational_background',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='past_professional_activities',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='professional_status',
        ),
        migrations.AddField(
            model_name='admission',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'private'), ('PUBLIC', 'public'), ('ASSOCIATIVE', 'associative'), ('HEALTH', 'health'), ('OTHER', 'other')], max_length=50, verbose_name='activity_sector'),
        ),
        migrations.AddField(
            model_name='admission',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='reference.Country', verbose_name='citizenship'),
        ),
        migrations.AddField(
            model_name='admission',
            name='current_employer',
            field=models.CharField(blank=True, max_length=50, verbose_name='current_employer'),
        ),
        migrations.AddField(
            model_name='admission',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=50, verbose_name='current_occupation'),
        ),
        migrations.AddField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='admission',
            name='high_school_diploma',
            field=models.BooleanField(default=False, verbose_name='high_school_diploma'),
        ),
        migrations.AddField(
            model_name='admission',
            name='high_school_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='high_school_graduation_year'),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_degree_field',
            field=models.CharField(blank=True, max_length=50, verbose_name='last_degree_field'),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_degree_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='last_degree_graduation_year'),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_degree_institution',
            field=models.CharField(blank=True, max_length=50, verbose_name='last_degree_institution'),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_degree_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='last_degree_level'),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_educational_background',
            field=models.TextField(blank=True, verbose_name='other_educational_background'),
        ),
        migrations.AddField(
            model_name='admission',
            name='past_professional_activities',
            field=models.TextField(blank=True, verbose_name='past_professional_activities'),
        ),
        migrations.AddField(
            model_name='admission',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone_mobile'),
        ),
        migrations.AddField(
            model_name='admission',
            name='professional_status',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'employee'), ('SELF_EMPLOYED', 'self_employed'), ('JOB_SEEKER', 'job_seeker'), ('PUBLIC_SERVANT', 'public_servant'), ('OTHER', 'other')], max_length=50, verbose_name='professional_status'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('waiting', 'waiting'), ('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='continuingeducationperson',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), verbose_name='birth_date'),
        ),
    ]
