# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 15:46
from __future__ import unicode_literals

import continuing_education.models.file
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0025_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='reference.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('ASSOCIATIVE', 'Associative'), ('HEALTH', 'Health'), ('OTHER', 'Other')], max_length=50, verbose_name='Activity sector'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='assessment_presented',
            field=models.BooleanField(default=False, verbose_name='Assessment presented'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='assessment_succeeded',
            field=models.BooleanField(default=False, verbose_name='Assessment succeeded'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_customized_mail',
            field=models.BooleanField(default=False, verbose_name='Awareness customized mail'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_emailing',
            field=models.BooleanField(default=False, verbose_name='Awareness emailing'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_facebook',
            field=models.BooleanField(default=False, verbose_name='Awareness Facebook'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_formation_website',
            field=models.BooleanField(default=False, verbose_name='Awareness formation website'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_linkedin',
            field=models.BooleanField(default=False, verbose_name='Awareness LinkedIn'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_press',
            field=models.BooleanField(default=False, verbose_name='Awareness press'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='awareness_ucl_website',
            field=models.BooleanField(default=False, verbose_name='Awareness UCL website'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='continuing_education.Address', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='children_number',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Children number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='reference.Country', verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='company_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='current_employer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Current employer'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Current occupation'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='formation',
            field=models.CharField(max_length=50, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='formation_spreading',
            field=models.BooleanField(default=False, verbose_name='Formation spreading'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='head_office_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Head office name'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='high_school_diploma',
            field=models.BooleanField(default=False, verbose_name='High school diploma'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='high_school_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='High school graduation year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID card number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_degree_field',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last degree field'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_degree_graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last degree graduation year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_degree_institution',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last degree institution'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_degree_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last degree level'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('LEGAL_COHABITANT', 'Legal cohabitant')], max_length=255, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='national_registry_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='National registry number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='noma',
            field=models.CharField(blank=True, max_length=255, verbose_name='NOMA'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='other_educational_background',
            field=models.TextField(blank=True, verbose_name='Other educational background'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='past_professional_activities',
            field=models.TextField(blank=True, verbose_name='Past professional activities'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='payment_complete',
            field=models.BooleanField(default=False, verbose_name='Payment complete'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='person_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.ContinuingEducationPerson', verbose_name='Person information'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_noma',
            field=models.CharField(blank=True, max_length=255, verbose_name='Previous NOMA'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_ucl_registration',
            field=models.BooleanField(default=False, verbose_name='Previous ucl registration'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='prior_experience_validation',
            field=models.BooleanField(default=False, verbose_name='Prior experience validation'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='professional_impact',
            field=models.TextField(blank=True, verbose_name='Professional impact'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='professional_status',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('SELF_EMPLOYED', 'Self employed'), ('JOB_SEEKER', 'Job seeker'), ('PUBLIC_SERVANT', 'Public servant'), ('OTHER', 'Other')], max_length=50, verbose_name='Professional status'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_complete',
            field=models.BooleanField(default=False, verbose_name='Registration complete'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('PROFESSIONAL', 'Professional')], max_length=50, verbose_name='Registration type'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_address', to='continuing_education.Address', verbose_name='Residence address'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='residence_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Residence phone'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sessions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sessions'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spouse name'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='use_address_for_billing',
            field=models.BooleanField(default=False, verbose_name='Use address for billing'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='use_address_for_post',
            field=models.BooleanField(default=False, verbose_name='Use address for post'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='continuingeducationperson',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_country', to='reference.Country', verbose_name='Birth country'),
        ),
        migrations.AlterField(
            model_name='continuingeducationperson',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='continuingeducationperson',
            name='birth_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Birth location'),
        ),
        migrations.AlterField(
            model_name='file',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Admission', verbose_name='Admission'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=continuing_education.models.file.admission_directory_path, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
        migrations.RunSQL('UPDATE continuing_education_admission SET state=initcap(state)')
    ]
