# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0028_auto_20181204_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
