# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0030_admission_state_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person', verbose_name='Uploaded by'),
        ),
    ]
