# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-17 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0033_auto_20190116_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='AdmissionFile',
        ),
    ]
