# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0034_file_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_category',
            field=models.CharField(choices=[('Document', 'Document'), ('Invoice', 'Facture'), ('Participant', 'Participant')], default='Document', max_length=20),
        ),
    ]
