# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0034_auto_20190117_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfile',
            name='file_category',
            field=models.CharField(choices=[('Document', 'Document'), ('Invoice', 'Invoice'), ('Student', 'Student')], default='Document', max_length=20),
        ),
    ]
