# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0035_auto_20190122_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_category',
            field=models.CharField(choices=[('Document', 'Document'), ('Invoice', 'Invoice'), ('Participant', 'Participant')], default='Document', max_length=20),
        ),
    ]
