# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0037_admission_registration_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='AdmissionFile',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='registration_state',
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Registration submitted', 'Registration submitted')], default='Draft', max_length=50, verbose_name='State'),
        ),
    ]
