# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0038_auto_20190124_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='registration_complete',
        ),
        migrations.AddField(
            model_name='admission',
            name='ucl_registration_complete',
            field=models.BooleanField(default=False, verbose_name='UCL registration complete'),
        ),
    ]
