# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-06 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0040_auto_20190201_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'permissions': (('can_access_admission', 'Can consult IUFC admission information'), ('can_validate_registration', 'Can validate IUFC registration file'))},
        ),
    ]
