# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0041_auto_20190206_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='AdmissionFile',
        ),
    ]
