# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0042_auto_20190214_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
