# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0043_admission_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='registration_file_received',
            field=models.BooleanField(default=False, verbose_name='Registration file received'),
        ),
    ]
