# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-04 11:54
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0047_admission_diploma_produced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
