# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 13:29
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0433_auto_20190305_1329'),
        ('continuing_education', '0048_auto_20190304_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuingEducationTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('education_group_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continuing_education.ContinuingEducationTraining')),
            ],
        ),
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='managers',
            field=models.ManyToManyField(through='continuing_education.PersonTraining', to='base.Person'),
        ),
    ]
