# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 13:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0433_auto_20190305_1329'),
        ('continuing_education', '0049_auto_20190305_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuingeducationtraining',
            name='education_group_year',
        ),
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='education_group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
    ]
