# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0050_auto_20190305_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='continuing_education.ContinuingEducationTraining', verbose_name='Formation'),
        ),
    ]
