# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0050_auto_20190305_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontraining',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='continuing_education.ContinuingEducationTraining', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='continuing_education.ContinuingEducationTraining', verbose_name='Formation'),
        ),
    ]
