# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0052_auto_20190311_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontraining',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
