# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0054_auto_20190328_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
