# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0055_auto_20190404_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='awareness_former_students',
            field=models.BooleanField(default=False, verbose_name='Awareness former students'),
        ),
        migrations.AddField(
            model_name='admission',
            name='awareness_friends',
            field=models.BooleanField(default=False, verbose_name='Awareness friends'),
        ),
        migrations.AddField(
            model_name='admission',
            name='awareness_moocs',
            field=models.BooleanField(default=False, verbose_name='Awareness Moocs'),
        ),
        migrations.AddField(
            model_name='admission',
            name='awareness_word_of_mouth',
            field=models.BooleanField(default=False, verbose_name='Awareness word of mouth'),
        ),
    ]
