# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0061_auto_20190425_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='alternate_notification_email_addresses',
            field=models.TextField(default='', verbose_name='Alternate notification email addresses'),
        ),
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='send_notification_emails',
            field=models.BooleanField(default=True, verbose_name='Send notification emails'),
        ),
    ]
