# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0062_auto_20190426_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='condition_of_acceptance',
            field=models.TextField(blank=True, verbose_name='Condition of acceptance'),
        ),
    ]
