# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0063_admission_condition_of_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationtraining',
            name='alternate_notification_email_addresses',
            field=models.TextField(blank=True, default='', verbose_name='Alternate notification email addresses'),
        ),
    ]
