# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0063_admission_condition_of_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='condition_of_acceptance',
            field=models.TextField(blank=True, null=True, verbose_name='Condition of acceptance'),
        ),
    ]
