# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0065_auto_20190508_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Registration submitted', 'Registration submitted'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50, verbose_name='State'),
        ),
    ]
