# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 09:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0066_auto_20190513_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='postal_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.Address'),
        ),
    ]
