# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0067_continuingeducationtraining_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional information'),
        ),
    ]
