# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0068_admission_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationtraining',
            name='additional_information_label',
            field=models.TextField(blank=True, default='', help_text='Leave empty if training does not require additional information', verbose_name='Additional information label'),
        ),
    ]
