# Generated by Django 2.2.5 on 2019-10-01 16:58

import continuing_education.models.file
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0070_admission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfile',
            name='path',
            field=models.FileField(upload_to=continuing_education.models.file.admission_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'gif', 'jpeg', 'jpg', 'tex', 'xls', 'xlsx', 'doc', 'docx', 'odt', 'txt', 'pdf', 'png', 'pptx', 'ppt', 'rtf'])], verbose_name='Path'),
        ),
    ]
