# Generated by Django 2.2.5 on 2019-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0072_auto_20191014_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='name',
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Accepted (no registration required)', 'Accepted (no registration required)'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Registration submitted', 'Registration submitted'), ('Validated', 'Validated'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50, verbose_name='State'),
        ),
    ]
