# Generated by Django 2.2.10 on 2020-03-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0075_auto_20200310_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ('formation', 'person_information'), 'permissions': (('validate_registration', 'Validate IUFC registration file'), ('change_received_file_state', 'Change received file state'))},
        ),
    ]
