# Generated by Django 2.2.10 on 2020-03-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0077_auto_20200316_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontraining',
            options={'default_permissions': ['view', 'add', 'delete']},
        ),
    ]
