# Generated by Django 2.2.10 on 2020-03-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0078_continuingeducationmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuingeducationmanager',
            options={'verbose_name': 'Continuing education manager', 'verbose_name_plural': 'Continuing education managers'},
        ),
        migrations.AlterModelOptions(
            name='persontraining',
            options={'default_permissions': ['view', 'add', 'delete']},
        ),
    ]
