# Generated by Django 2.2.10 on 2020-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0078_auto_20200320_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='ucl_registration_error',
            field=models.CharField(blank=True, choices=[('IUFC_NO_ERROR', 'No error'), ('IUFC_NOM_TROP_LONG', 'Too long name'), ('IUFC_PRENOM_TROP_LONG', 'Too long first name'), ('IUFC_ADRESSE_TROP_LONGUE', 'Too long address'), ('IUFC_NOM_MANQUANT', 'Missing name'), ('IUFC_PRENOM_MANQUANT', 'Missing first name'), ('IUFC_ANNEE_MANQUANTE', 'Missing year'), ('IUFC_PROGRAMME_MANQUANT', 'Missing program'), ('IUFC_NATIONALITE_MANQUANTE', 'Missing citizenship'), ('IUFC_PAYS_NAISSANCE_MANQUANT', 'Missing birth country'), ('IUFC_INSCRIPTION_DEJA_TRAITEE', 'Registration already processed'), ('IUFC_CREATION_NOMA_ECHOUEE', 'NOMA creation failed')], default='IUFC_NO_ERROR', max_length=50, null=True, verbose_name='UCLouvain registration error'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ucl_registration_complete',
            field=models.CharField(blank=True, choices=[('INIT_STATE', 'Initial state'), ('SENDED', 'Sended'), ('INSCRIT', 'Registered'), ('DEMANDE', 'On demand'), ('REJECTED', 'Rejected'), ('NON_RENSEIGNE', 'Uninformed'), ('CONDITION', 'Provisional'), ('ANNULATION_ETD', 'Cancellation (ETD)'), ('ANNULATION_UCL', 'Cancellation (UNIV)'), ('EXCLUSION', 'Exclusion'), ('CESSATION', 'Cessation'), ('DECES', 'Death'), ('ERREUR', 'Error'), ('INTENTION_ECHANGE', 'Register intention'), ('ANNULATION_ECHANGE', 'Intention cancellation'), ('REINSCRIPTION_WEB', 'Internet re-registration'), ('ANNULATION_IP', 'IP Cancellation'), ('REFUS', 'Refusal'), ('CYCLE', 'Cycle'), ('VALISE_CREDITS', 'Valued crédits')], default='INIT_STATE', max_length=50, verbose_name='UCLouvain registration complete'),
        ),
    ]
