# Generated by Django 2.2.10 on 2020-03-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0508_auto_20200318_1251'),
        ('continuing_education', '0079_continuingeducationmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuingeducationmanager',
            options={'verbose_name': 'Continuing education manager', 'verbose_name_plural': 'Continuing education managers'},
        ),
        migrations.CreateModel(
            name='ContinuingEducationStudentWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Continuing education student worker',
                'verbose_name_plural': 'Continuing education student worker',
            },
        ),
    ]
