# Generated by Django 2.2.10 on 2020-03-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0080_auto_20200323_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'default_permissions': ['view', 'change'], 'ordering': ('formation', 'person_information'), 'permissions': (('validate_registration', 'Validate IUFC registration file'), ('change_received_file_state', 'Change received file state'), ('link_admission_to_academic_year', 'Link an admission to an academic year'), ('inject_admission_to_epc', 'Inject an admission to EPC'), ('mark_diploma_produced', 'Mark an admission diploma has been produced'), ('send_notification', 'Send a notification related to an admission'), ('archive_admission', 'Archive an admission'), ('export_admission', 'Export an admission into XLSX file'), ('cancel_admission', 'Cancel an admission'))},
        ),
        migrations.AlterModelOptions(
            name='continuingeducationtraining',
            options={'default_permissions': ['view', 'change'], 'ordering': ('education_group',), 'permissions': (('manage_all_trainings', 'Manage all continuing education trainings'), ('set_training_active', 'Set a continuing education training as active'))},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={'default_permissions': ['view'], 'permissions': (('export_prospect', 'Export a prospect into XLSX file'),)},
        ),
    ]
