# Generated by Django 2.2.10 on 2020-03-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0508_auto_20200325_1013'),
        ('continuing_education', '0081_auto_20200330_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuingeducationstudentworker',
            options={'verbose_name': 'Continuing education student worker', 'verbose_name_plural': 'Continuing education student workers'},
        ),
        migrations.CreateModel(
            name='ContinuingEducationTrainingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Continuing education training manager',
                'verbose_name_plural': 'Continuing education training managers',
            },
        ),
    ]
