# Generated by Django 2.2.10 on 2020-04-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0508_auto_20200325_1013'),
        ('continuing_education', '0082_auto_20200330_1220'),
    ]

    def migrate_person_training_into_continuing_education_training_manager(apps, schema_editor):
        PersonTraining = apps.get_model(
            'continuing_education', 'PersonTraining'
        )
        ContinuingEducationTrainingManager = apps.get_model(
            'continuing_education', 'ContinuingEducationTrainingManager'
        )
        db_alias = schema_editor.connection.alias
        data = PersonTraining.objects.using(db_alias).all()
        ContinuingEducationTrainingManager.objects.using(db_alias).bulk_create([
            ContinuingEducationTrainingManager(person=d.person, training=d.training)
        ] for d in data)

    operations = [
        migrations.AlterModelOptions(
            name='continuingeducationtrainingmanager',
            options={'default_permissions': ['view', 'add', 'delete'], 'verbose_name': 'Continuing education training manager', 'verbose_name_plural': 'Continuing education training managers'},
        ),
        migrations.AddField(
            model_name='continuingeducationtrainingmanager',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.ContinuingEducationTraining'),
        ),
        migrations.AlterField(
            model_name='continuingeducationtraining',
            name='managers',
            field=models.ManyToManyField(through='continuing_education.ContinuingEducationTrainingManager', to='base.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='continuingeducationtrainingmanager',
            unique_together={('person', 'training')},
        ),
        migrations.RunPython(migrate_person_training_into_continuing_education_training_manager),
        migrations.DeleteModel(
            name='PersonTraining',
        ),
    ]
