# Generated by Django 2.2.13 on 2021-01-27 11:19

import django.core.validators
from django.db import migrations, models

import osis_common.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0083_auto_20201027_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='national_registry_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.'), osis_common.utils.validators.belgium_national_register_number_validator], verbose_name='National registry number'),
        ),
    ]
