# Generated by Django 2.2.10 on 2021-04-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0583_auto_20210324_0954'),
        ('continuing_education', '0084_auto_20210127_1119'),
    ]

    def migrate_person_training_into_continuing_education_training_manager(apps, schema_editor):
        PersonTraining = apps.get_model(
            'continuing_education', 'PersonTraining'
        )
        ContinuingEducationTrainingManager = apps.get_model(
            'continuing_education', 'ContinuingEducationTrainingManager'
        )
        db_alias = schema_editor.connection.alias
        data = PersonTraining.objects.using(db_alias).all()
        ContinuingEducationTrainingManager.objects.using(db_alias).bulk_create(
            [ContinuingEducationTrainingManager(person=d.person, training=d.training) for d in data]
        )

    operations = [
        migrations.CreateModel(
            name='ContinuingEducationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Continuing education manager',
                'verbose_name_plural': 'Continuing education managers',
            },
        ),
        migrations.CreateModel(
            name='ContinuingEducationStudentWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Continuing education student worker',
                'verbose_name_plural': 'Continuing education student workers',
            },
        ),
        migrations.CreateModel(
            name='ContinuingEducationTrainingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Continuing education training manager',
                'verbose_name_plural': 'Continuing education training managers',
                'default_permissions': ['view', 'add', 'delete'],
            },
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'default_permissions': ['view', 'change'], 'ordering': ('formation', 'person_information'), 'permissions': (('validate_registration', 'Validate IUFC registration file'), ('change_received_file_state', 'Change received file state'), ('link_admission_to_academic_year', 'Link an admission to an academic year'), ('inject_admission_to_epc', 'Inject an admission to EPC'), ('mark_diploma_produced', 'Mark an admission diploma has been produced'), ('send_notification', 'Send a notification related to an admission'), ('archive_admission', 'Archive an admission'), ('export_admission', 'Export an admission into XLSX file'), ('cancel_admission', 'Cancel an admission'))},
        ),
        migrations.AlterModelOptions(
            name='continuingeducationtraining',
            options={'default_permissions': ['view', 'change'], 'ordering': ('education_group',), 'permissions': (('manage_all_trainings', 'Manage all continuing education trainings'), ('set_training_active', 'Set a continuing education training as active'))},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={'default_permissions': ['view'], 'permissions': (('export_prospect', 'Export a prospect into XLSX file'),)},
        ),
        migrations.AlterField(
            model_name='continuingeducationtraining',
            name='managers',
            field=models.ManyToManyField(through='continuing_education.ContinuingEducationTrainingManager', to='base.Person'),
        ),
        migrations.AddField(
            model_name='continuingeducationtrainingmanager',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='continuing_education.ContinuingEducationTraining'),
        ),
        migrations.AlterUniqueTogether(
            name='continuingeducationtrainingmanager',
            unique_together={('person', 'training')},
        ),
        migrations.RunPython(migrate_person_training_into_continuing_education_training_manager, elidable=True),
        migrations.DeleteModel(
            name='PersonTraining',
        ),
    ]
