# Generated by Django 3.1.1 on 2021-04-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0585_auto_20210420_0845'),
        ('continuing_education', '0085_auto_20210423_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
        migrations.AlterField(
            model_name='continuingeducationstudentworker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
        migrations.AlterField(
            model_name='continuingeducationtrainingmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
    ]
